#
# Authors: Krix Apolinario <krixapolinario@gmail.com>
#
# Description: Simples Ansible Playbook to install a Docker CE on Cent OS 7
#

---

- name: Check OS version and family
  fail:
      msg: This playbook is only functional on CentOS 7 distribution
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version | version_compare('7', '!=')

- name: Copy repository files to yum.repos.d
  copy:
    src: etc/yum.repos.d/
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Install dependences
  yum: name={{ item }} state=latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Install Docker CE
  yum: 
    name: docker-ce 
    enablerepo: docker-ce-edge
    state: latest

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enable: yes 

- name: Download Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.14.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
